import Head from "next/head";
import Image from "next/image";
import Features from "../components/homepage/features/features";
import Footer from "../components/homepage/footer/footer";
import Header from "../components/homepage/header/header";
import Hero from "../components/homepage/hero/hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mr Candie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/candie logo jpg.jpg" />
      </Head>
      <Header />
      <Hero />
      <Features />
      <Footer />
    </div>
  );
}
